server:
  port: 8761

spring:
  application:
    name: eureka

eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
  server:
    enable-self-preservation: false
    response-cache-update-interval-ms: 5000
