# spring.application.name : Application Name ?? (front-end? ??)
# spring.datasource : ?? DB ??
# spring.mvc.hiddenmethod.filter.enabled : MVC ????? Hidden Method ?? ?? ?? (Form ? ?? PUT, DELETE ????? ? ? ???)
spring:
  application:
    name: board
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://34.125.170.174:3306/mysql?serverTimezone=UTC&characterEncoding=UTF-8
    username: dooyoungk
    password: 1
  mvc:
    hiddenmethod:
      filter:
        enabled: true

# mybatis ?? (mybatis-config.xml ?? ???? ?? ??)
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations:
    - /mapper/**/*.xml

# server.port : 8080 ?? ??
# server.servlet.encoding : Embedded Tomcat? ??? ??
# server.shutdown
#  : Spring Boot 2.3 ?? ???? ???? ??
#  : ????? ??? ? ??? ????? ?? ??? 30?. ?? ???? ??? spring.lifecycle.timeout-per-shutdown-phase=1m ?? ?? ??
server:
  port: 8081
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  shutdown: graceful


# management.endpoints.web.exposure.include : Actuator Open URI ??. ???? "health,info" ??
management:
  endpoints:
    web:
      exposure:
        include: "health,info"

eureka:
  client:
    register-with-eureka: true  #Eureka server에 등록하고 검색할지에 대한 설정
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka #http://localhost:8761/eureka
